/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LLEDO
 */
public class VistaPrincipal extends javax.swing.JFrame {

    public VistaPrincipal() {
        initComponents();
        String rutaMarcas = "C:\\Users\\enmanuel.esteban.lle\\Documents\\NetBeansProjects\\mobileProviderApp\\src\\sources\\ficheros\\brands\\brands.csv";
        cargarItemsDesdeArchivo(rutaMarcas, CBox_brands);
        
        String rutaModelos = "C:\\Users\\enmanuel.esteban.lle\\Documents\\NetBeansProjects\\mobileProviderApp\\src\\sources\\ficheros\\models\\models_Apple.csv";
        cargarItemsDesdeArchivo(rutaModelos,CBox_models);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Options = new javax.swing.JPanel();
        lbl_nameUserSesion = new javax.swing.JLabel();
        lbl_profileImg = new javax.swing.JLabel();
        lbl_userConnected = new javax.swing.JLabel();
        lbl_iconConnected = new javax.swing.JLabel();
        lbl_backProfile = new javax.swing.JLabel();
        jPanel_Dashboard = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        lbl_dashboard_options = new javax.swing.JLabel();
        jPanel_Catalog = new javax.swing.JPanel();
        lbl_catalog = new javax.swing.JLabel();
        lbl_catalog_options = new javax.swing.JLabel();
        jPanel_AboutUs = new javax.swing.JPanel();
        lbl_AboutUs = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_iconBanner = new javax.swing.JLabel();
        lbl_tittleBanner = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_banner = new javax.swing.JLabel();
        jTabbedPane_Main = new javax.swing.JTabbedPane();
        jPanel_dashboard = new javax.swing.JPanel();
        lbl_outPanelBrands = new javax.swing.JLabel();
        lbl_outPanelCatalog = new javax.swing.JLabel();
        lbl_outPanelAboutUs = new javax.swing.JLabel();
        lbl_tittleBrands = new javax.swing.JLabel();
        btn_logoApple = new javax.swing.JButton();
        btn_logoHuawei = new javax.swing.JButton();
        btn_logoSamsung = new javax.swing.JButton();
        jScrollPane_Brands = new javax.swing.JScrollPane();
        jTextArea_panelBrands = new javax.swing.JTextArea();
        btn_panelBrands = new javax.swing.JButton();
        lbl_panelBrands = new javax.swing.JLabel();
        lbl_tittleCatalog = new javax.swing.JLabel();
        jScrollPane_Catalog = new javax.swing.JScrollPane();
        jTextArea_panelBrand = new javax.swing.JTextArea();
        btn_panelCatalog = new javax.swing.JButton();
        lbl_panelCatalog = new javax.swing.JLabel();
        lbl_tittleAuboutUs = new javax.swing.JLabel();
        jScrollPane_AboutUs = new javax.swing.JScrollPane();
        jTextArea_panelAboutUs = new javax.swing.JTextArea();
        btn_panelAboutUs = new javax.swing.JButton();
        lbl_panelAboutUs = new javax.swing.JLabel();
        jPanel_catalog = new javax.swing.JPanel();
        jPanel_search = new javax.swing.JPanel();
        lbl_tittleBrand_search = new javax.swing.JLabel();
        textField_brandSearch = new javax.swing.JTextField();
        CBox_brands = new javax.swing.JComboBox<>();
        lbl_tittleModels_search = new javax.swing.JLabel();
        textField_modelSearch = new javax.swing.JTextField();
        CBox_models = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        lbl_messageOkorError = new javax.swing.JLabel();
        jPanel_details = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane_Brands1 = new javax.swing.JScrollPane();
        jTextArea_panelBrands1 = new javax.swing.JTextArea();
        lbl_imageSmartphone = new javax.swing.JLabel();
        jPanel_statsStock = new javax.swing.JPanel();
        lbl_tittleStats = new javax.swing.JLabel();
        lbl_tittleStats1 = new javax.swing.JLabel();
        jProgressBar_stock = new javax.swing.JProgressBar();
        jPanel_aboutUs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Options.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nameUserSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nameUserSesion.setText("Usuario");
        jPanel_Options.add(lbl_nameUserSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 10));

        lbl_profileImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/panel_opciones/perfil.png"))); // NOI18N
        jPanel_Options.add(lbl_profileImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 130));

        lbl_userConnected.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl_userConnected.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userConnected.setText("Conected");
        jPanel_Options.add(lbl_userConnected, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 20));

        lbl_iconConnected.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl_iconConnected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/panel_opciones/green.png"))); // NOI18N
        lbl_iconConnected.setText("x");
        jPanel_Options.add(lbl_iconConnected, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 20, 20));

        lbl_backProfile.setBackground(new java.awt.Color(204, 255, 255));
        lbl_backProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/banner/banner.jpg"))); // NOI18N
        lbl_backProfile.setMaximumSize(new java.awt.Dimension(250, 180));
        lbl_backProfile.setMinimumSize(new java.awt.Dimension(250, 180));
        jPanel_Options.add(lbl_backProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 210));

        lbl_dashboard.setText("DASHBOARD");

        lbl_dashboard_options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/icons/dashboard-icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel_DashboardLayout = new javax.swing.GroupLayout(jPanel_Dashboard);
        jPanel_Dashboard.setLayout(jPanel_DashboardLayout);
        jPanel_DashboardLayout.setHorizontalGroup(
            jPanel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_dashboard_options)
                .addGap(27, 27, 27)
                .addComponent(lbl_dashboard)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel_DashboardLayout.setVerticalGroup(
            jPanel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DashboardLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_dashboard_options)
                    .addComponent(lbl_dashboard))
                .addGap(18, 18, 18))
        );

        jPanel_Options.add(jPanel_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 60));

        lbl_catalog.setText("CATALOG");

        lbl_catalog_options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/icons/catalog-icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel_CatalogLayout = new javax.swing.GroupLayout(jPanel_Catalog);
        jPanel_Catalog.setLayout(jPanel_CatalogLayout);
        jPanel_CatalogLayout.setHorizontalGroup(
            jPanel_CatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CatalogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_catalog_options)
                .addGap(31, 31, 31)
                .addComponent(lbl_catalog)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel_CatalogLayout.setVerticalGroup(
            jPanel_CatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CatalogLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel_CatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_catalog_options)
                    .addComponent(lbl_catalog))
                .addGap(18, 18, 18))
        );

        jPanel_Options.add(jPanel_Catalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, 60));

        lbl_AboutUs.setText("ABOUT US");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/icons/aboutUs-icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel_AboutUsLayout = new javax.swing.GroupLayout(jPanel_AboutUs);
        jPanel_AboutUs.setLayout(jPanel_AboutUsLayout);
        jPanel_AboutUsLayout.setHorizontalGroup(
            jPanel_AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AboutUsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addGap(27, 27, 27)
                .addComponent(lbl_AboutUs)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel_AboutUsLayout.setVerticalGroup(
            jPanel_AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AboutUsLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel_AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(lbl_AboutUs))
                .addGap(18, 18, 18))
        );

        jPanel_Options.add(jPanel_AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, 60));

        getContentPane().add(jPanel_Options, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 780));

        lbl_iconBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/panel_opciones/dashboard.jpg"))); // NOI18N
        getContentPane().add(lbl_iconBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 50, 50));

        lbl_tittleBanner.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_tittleBanner.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tittleBanner.setText("DASHBOARD");
        getContentPane().add(lbl_tittleBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        lbl_minimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_minimize.setForeground(new java.awt.Color(255, 255, 255));
        lbl_minimize.setText("-");
        getContentPane().add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, -1));

        lbl_exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setText("X");
        getContentPane().add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        lbl_banner.setBackground(new java.awt.Color(204, 255, 255));
        lbl_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/banner/banner.jpg"))); // NOI18N
        getContentPane().add(lbl_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1080, 90));

        jTabbedPane_Main.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane_Main.setToolTipText("");
        jTabbedPane_Main.setName(""); // NOI18N

        jPanel_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_outPanelBrands.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_outPanelBrands.setText("OUR BRANDS");
        jPanel_dashboard.add(lbl_outPanelBrands, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 22, -1, -1));

        lbl_outPanelCatalog.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_outPanelCatalog.setText("CATALOG");
        jPanel_dashboard.add(lbl_outPanelCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 22, -1, -1));

        lbl_outPanelAboutUs.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_outPanelAboutUs.setText("ABOUT US");
        jPanel_dashboard.add(lbl_outPanelAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        lbl_tittleBrands.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tittleBrands.setText("Top Brands");
        jPanel_dashboard.add(lbl_tittleBrands, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 20));

        btn_logoApple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/marcas/huawei-logo.jpg"))); // NOI18N
        jPanel_dashboard.add(btn_logoApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 70, 90));

        btn_logoHuawei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/marcas/samsung-logo.jpg"))); // NOI18N
        jPanel_dashboard.add(btn_logoHuawei, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 130, 80));

        btn_logoSamsung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/marcas/Apple_logo.jpg"))); // NOI18N
        jPanel_dashboard.add(btn_logoSamsung, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, 90));

        jTextArea_panelBrands.setColumns(20);
        jTextArea_panelBrands.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_panelBrands.setLineWrap(true);
        jTextArea_panelBrands.setRows(5);
        jTextArea_panelBrands.setText("Consulta en tiempo real la disponibilidad de nuestros modelos. Mantenemos un stock actualizado para que siempre encuentres lo que necesitas, desde los últimos lanzamientos hasta opciones económicas y confiables.");
        jTextArea_panelBrands.setToolTipText("Descripcion");
        jTextArea_panelBrands.setWrapStyleWord(true);
        jTextArea_panelBrands.setAutoscrolls(false);
        jTextArea_panelBrands.setBorder(null);
        jTextArea_panelBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextArea_panelBrands.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea_panelBrands.setHighlighter(null);
        jTextArea_panelBrands.setKeymap(null);
        jTextArea_panelBrands.setName(""); // NOI18N
        jTextArea_panelBrands.setVerifyInputWhenFocusTarget(false);
        jScrollPane_Brands.setViewportView(jTextArea_panelBrands);
        jTextArea_panelBrands.getAccessibleContext().setAccessibleDescription("");

        jPanel_dashboard.add(jScrollPane_Brands, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 220, 140));

        btn_panelBrands.setText("See more");
        jPanel_dashboard.add(btn_panelBrands, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, 30));

        lbl_panelBrands.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/figuras/lateral-gris.jpg"))); // NOI18N
        jPanel_dashboard.add(lbl_panelBrands, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 399, 487));

        lbl_tittleCatalog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tittleCatalog.setText("Our Stock");
        jPanel_dashboard.add(lbl_tittleCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jTextArea_panelBrand.setColumns(20);
        jTextArea_panelBrand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_panelBrand.setLineWrap(true);
        jTextArea_panelBrand.setRows(5);
        jTextArea_panelBrand.setText("Explora nuestra selección de móviles: gama alta, media y de entrada. Trabajamos con las marcas más reconocidas del mercado para ofrecer variedad, calidad y tecnología de punta para cada tipo de cliente.");
        jTextArea_panelBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane_Catalog.setViewportView(jTextArea_panelBrand);

        jPanel_dashboard.add(jScrollPane_Catalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 220, 140));

        btn_panelCatalog.setText("See more");
        jPanel_dashboard.add(btn_panelCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, 30));

        lbl_panelCatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/figuras/lateral-gris.jpg"))); // NOI18N
        jPanel_dashboard.add(lbl_panelCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 329, 487));

        lbl_tittleAuboutUs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tittleAuboutUs.setText("Our company");
        jPanel_dashboard.add(lbl_tittleAuboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        jTextArea_panelAboutUs.setColumns(20);
        jTextArea_panelAboutUs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_panelAboutUs.setLineWrap(true);
        jTextArea_panelAboutUs.setRows(5);
        jTextArea_panelAboutUs.setText("Somos tu proveedor de confianza en tecnología móvil. Ofrecemos atención personalizada, asesoría comercial y logística eficiente para que tu negocio siempre esté conectado y actualizado.");
        jTextArea_panelAboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane_AboutUs.setViewportView(jTextArea_panelAboutUs);

        jPanel_dashboard.add(jScrollPane_AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 220, 140));

        btn_panelAboutUs.setText("See more");
        jPanel_dashboard.add(btn_panelAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, -1, 30));

        lbl_panelAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/figuras/lateral-gris.jpg"))); // NOI18N
        jPanel_dashboard.add(lbl_panelAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 329, 487));

        jTabbedPane_Main.addTab("Dashboard", jPanel_dashboard);

        jPanel_catalog.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_catalog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_search.setBackground(new java.awt.Color(204, 204, 204));

        lbl_tittleBrand_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tittleBrand_search.setText("BRAND");

        textField_brandSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_brandSearchActionPerformed(evt);
            }
        });

        CBox_brands.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBox_brands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBox_brandsActionPerformed(evt);
            }
        });

        lbl_tittleModels_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tittleModels_search.setText("MODEL");

        textField_modelSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_modelSearchActionPerformed(evt);
            }
        });

        CBox_models.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBox_models.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBox_modelsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("UNITS");

        jButton2.setText("BUY");

        lbl_messageOkorError.setText("Mensaje de confirmacion / error");

        javax.swing.GroupLayout jPanel_searchLayout = new javax.swing.GroupLayout(jPanel_search);
        jPanel_search.setLayout(jPanel_searchLayout);
        jPanel_searchLayout.setHorizontalGroup(
            jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_brandSearch)
                    .addComponent(textField_modelSearch)
                    .addGroup(jPanel_searchLayout.createSequentialGroup()
                        .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBox_brands, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tittleModels_search)
                            .addComponent(CBox_models, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tittleBrand_search)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_searchLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_searchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_messageOkorError)
                .addGap(75, 75, 75))
        );
        jPanel_searchLayout.setVerticalGroup(
            jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tittleBrand_search)
                .addGap(14, 14, 14)
                .addComponent(textField_brandSearch)
                .addGap(8, 8, 8)
                .addComponent(CBox_brands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbl_tittleModels_search)
                .addGap(4, 4, 4)
                .addComponent(textField_modelSearch)
                .addGap(8, 8, 8)
                .addComponent(CBox_models, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_messageOkorError)
                .addGap(15, 15, 15))
        );

        jPanel_catalog.add(jPanel_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 340));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("SAMSUNG Galaxy A15 5G Smartphone 128 GB Blau");

        jTextArea_panelBrands1.setColumns(20);
        jTextArea_panelBrands1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_panelBrands1.setLineWrap(true);
        jTextArea_panelBrands1.setRows(5);
        jTextArea_panelBrands1.setText("Especificaciones Tecnicas");
        jTextArea_panelBrands1.setToolTipText("Descripcion");
        jTextArea_panelBrands1.setWrapStyleWord(true);
        jTextArea_panelBrands1.setAutoscrolls(false);
        jTextArea_panelBrands1.setBorder(null);
        jTextArea_panelBrands1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextArea_panelBrands1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea_panelBrands1.setHighlighter(null);
        jTextArea_panelBrands1.setKeymap(null);
        jTextArea_panelBrands1.setName(""); // NOI18N
        jTextArea_panelBrands1.setVerifyInputWhenFocusTarget(false);
        jScrollPane_Brands1.setViewportView(jTextArea_panelBrands1);

        lbl_imageSmartphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/modelos_samsung/model_samsung.jpg"))); // NOI18N
        lbl_imageSmartphone.setToolTipText("");

        javax.swing.GroupLayout jPanel_detailsLayout = new javax.swing.GroupLayout(jPanel_details);
        jPanel_details.setLayout(jPanel_detailsLayout);
        jPanel_detailsLayout.setHorizontalGroup(
            jPanel_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_detailsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_detailsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_imageSmartphone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane_Brands1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel_detailsLayout.setVerticalGroup(
            jPanel_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_detailsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(jPanel_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_imageSmartphone)
                    .addComponent(jScrollPane_Brands1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel_catalog.add(jPanel_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 540, 370));

        lbl_tittleStats.setText("Stats of Product");

        lbl_tittleStats1.setText("90 Disponibles");

        jProgressBar_stock.setForeground(new java.awt.Color(0, 153, 255));
        jProgressBar_stock.setToolTipText("Conteo");
        jProgressBar_stock.setValue(90);
        jProgressBar_stock.setBorder(null);
        jProgressBar_stock.setOpaque(true);

        javax.swing.GroupLayout jPanel_statsStockLayout = new javax.swing.GroupLayout(jPanel_statsStock);
        jPanel_statsStock.setLayout(jPanel_statsStockLayout);
        jPanel_statsStockLayout.setHorizontalGroup(
            jPanel_statsStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_statsStockLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_statsStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_tittleStats1)
                    .addComponent(lbl_tittleStats))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel_statsStockLayout.setVerticalGroup(
            jPanel_statsStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_statsStockLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_statsStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tittleStats)
                    .addComponent(jProgressBar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_tittleStats1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel_catalog.add(jPanel_statsStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 540, 80));

        jTabbedPane_Main.addTab("Catalog", jPanel_catalog);

        jPanel_aboutUs.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_aboutUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("We are your trusted mobile technology provider. We offer personalized support, sales consulting, and efficient logistics to keep your business connected and up-to-date.");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel_aboutUs.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 680, 160));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/logo_company.jpg"))); // NOI18N
        jPanel_aboutUs.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 200));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Project developed by: Ian Roca & Leo Ces Fragoso & Enmanuel Lledo");
        jPanel_aboutUs.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 560, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("All rights reserved © 2025");
        jPanel_aboutUs.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        jTabbedPane_Main.addTab("AboutUs", jPanel_aboutUs);

        getContentPane().add(jTabbedPane_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 1080, 690));
        jTabbedPane_Main.getAccessibleContext().setAccessibleName("Home");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBox_brandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBox_brandsActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_CBox_brandsActionPerformed

    private void textField_modelSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_modelSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_modelSearchActionPerformed

    private void textField_brandSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_brandSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_brandSearchActionPerformed

    private void CBox_modelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBox_modelsActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_CBox_modelsActionPerformed
    // funciones para integrar los datos desde ficheros CSV con litas en componentes JComboBox
    
     private void cargarItemsDesdeArchivo(String pathCSV, javax.swing.JComboBox <String> combo ) {
        File datos = new File(pathCSV);
        try (BufferedReader br = new BufferedReader(new FileReader(datos))) {
            DefaultComboBoxModel<String> archivoCast = new DefaultComboBoxModel<>();// casteo
            String linea;
            while ((linea = br.readLine()) != null) {
                archivoCast.addElement(linea); // Agregar cada línea como un ítem
            }
            combo.setModel(archivoCast); // Asignar el modelo al JComboBox

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
        }
    }
     
     // gestion de eventos e interaccion en listas 
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBox_brands;
    private javax.swing.JComboBox<String> CBox_models;
    private javax.swing.JButton btn_logoApple;
    private javax.swing.JButton btn_logoHuawei;
    private javax.swing.JButton btn_logoSamsung;
    private javax.swing.JButton btn_panelAboutUs;
    private javax.swing.JButton btn_panelBrands;
    private javax.swing.JButton btn_panelCatalog;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel_AboutUs;
    private javax.swing.JPanel jPanel_Catalog;
    private javax.swing.JPanel jPanel_Dashboard;
    private javax.swing.JPanel jPanel_Options;
    private javax.swing.JPanel jPanel_aboutUs;
    private javax.swing.JPanel jPanel_catalog;
    private javax.swing.JPanel jPanel_dashboard;
    private javax.swing.JPanel jPanel_details;
    private javax.swing.JPanel jPanel_search;
    private javax.swing.JPanel jPanel_statsStock;
    private javax.swing.JProgressBar jProgressBar_stock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_AboutUs;
    private javax.swing.JScrollPane jScrollPane_Brands;
    private javax.swing.JScrollPane jScrollPane_Brands1;
    private javax.swing.JScrollPane jScrollPane_Catalog;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane_Main;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea_panelAboutUs;
    private javax.swing.JTextArea jTextArea_panelBrand;
    private javax.swing.JTextArea jTextArea_panelBrands;
    private javax.swing.JTextArea jTextArea_panelBrands1;
    private javax.swing.JLabel lbl_AboutUs;
    private javax.swing.JLabel lbl_backProfile;
    private javax.swing.JLabel lbl_banner;
    private javax.swing.JLabel lbl_catalog;
    private javax.swing.JLabel lbl_catalog_options;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_dashboard_options;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_iconBanner;
    private javax.swing.JLabel lbl_iconConnected;
    private javax.swing.JLabel lbl_imageSmartphone;
    private javax.swing.JLabel lbl_messageOkorError;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JLabel lbl_nameUserSesion;
    private javax.swing.JLabel lbl_outPanelAboutUs;
    private javax.swing.JLabel lbl_outPanelBrands;
    private javax.swing.JLabel lbl_outPanelCatalog;
    private javax.swing.JLabel lbl_panelAboutUs;
    private javax.swing.JLabel lbl_panelBrands;
    private javax.swing.JLabel lbl_panelCatalog;
    private javax.swing.JLabel lbl_profileImg;
    private javax.swing.JLabel lbl_tittleAuboutUs;
    private javax.swing.JLabel lbl_tittleBanner;
    private javax.swing.JLabel lbl_tittleBrand_search;
    private javax.swing.JLabel lbl_tittleBrands;
    private javax.swing.JLabel lbl_tittleCatalog;
    private javax.swing.JLabel lbl_tittleModels_search;
    private javax.swing.JLabel lbl_tittleStats;
    private javax.swing.JLabel lbl_tittleStats1;
    private javax.swing.JLabel lbl_userConnected;
    private javax.swing.JTextField textField_brandSearch;
    private javax.swing.JTextField textField_modelSearch;
    // End of variables declaration//GEN-END:variables
}
